### ISSUE TITLE
Getting Started documentation doesn't work with MicroZig 0.15.0

### ISSUE THREAD

**Issue by Jdad5150** [ZigEmbeddedGroup/microzig#860]
Problem

The [Getting Started guide](https://microzig.tech/docs/getting-started/) shows example code that doesn't compile with the recommended MicroZig version (0.15.0).

## Steps to Reproduce

1. Follow the getting started guide exactly as written
2. Install MicroZig 0.15.0 as instructed:
   ```
   zig fetch --save https://github.com/ZigEmbeddedGroup/microzig/releases/download/0.15.0/microzig.tar.gz
   ```
3. Use the example code from the docs:
   ```zig
   const pin_config = rp2xxx.pins.GlobalConfiguration{
       .GPIO25 = .{
           .name = "led",
           .direction = .out,
       },
   };

   pub fn main() !void {
       const pins = pin_config.apply();

       while (true) {
           pins.led.toggle();
           time.sleep_ms(250);
       }
   }
   ```
4. Run `zig build`

## Expected Behavior

The code should compile and work as documented.

## Actual Behavior

Compilation fails with:
```
src/main.zig:17:13: error: type 'void' does not support field access
        pins.led.toggle();
        ~~~~^~~~
```

## Root Cause

In MicroZig 0.15.0, the `GlobalConfiguration.apply()` function returns `void`, not a struct with named pin fields. The function signature is:

```zig
pub fn apply(comptime config: GlobalConfiguration) void {
```

So `const pins = pin_config.apply()` results in `pins` having type `void`, which doesn't support field access.

## Environment

- Zig version: 0.15.2
- MicroZig version: 0.15.0 (as recommended in docs)
- Target: Raspberry Pi Pico (RP2040)

## Suggested Fix

Either:
1. Update the documentation to show code that works with 0.15.0 (using `gpio.num()` directly), or
2. Release a new version of MicroZig where `apply()` returns a struct with named pins, and update the docs to recommend that version

## Workaround

For anyone hitting this issue, here's working code for MicroZig 0.15.0:

```zig
const std = @import("std");
const microzig = @import("microzig");
const rp2xxx = microzig.hal;
const time = rp2xxx.time;
const gpio = rp2xxx.gpio;

pub fn main() !void {
    const led = gpio.num(25);
    led.set_function(.sio);
    led.set_direction(.out);

    while (true) {
        led.toggle();
        time.sleep_ms(250);
    }
}

**Comment by Grazfather** [comment]
Thanks for posting the workaround.

This is my fault, I updated the API and the docs, but the docs point to the release with the old API. The 'other' workaround is to simply pull Microzig from master.

We will likely cut a new release, at which points the docs will be corrected.

I'll keep this issue open for now.

**Comment by Jdad5150** [comment]
Okay thank you. It was actually a good issue for me to run into, it made me look more into the source code and learn what's going on under the hood. If there's anything you guys need help with let me know! I love Zig and coming from C for embedded, microzig has really been a breath of fresh air.

**Comment by Grazfather** [comment]
Lots of stuff going on if you look at all the PRs going through. I'd suggest hopping on the discord, 'cause that's where most of the discussion happens.
